messages:
  responses:
    start: "Для того, чтобы я сохранил твоё пожелание, тебе нужно просто его написать и отправить! :)"
    start_gifts: "Пора начинать дарить подарки!!!"
    add_wish: "Твоё пожелание успешно сохранено!"
    empty_wishes: "Список желаний пуст"
  errors:
    default: "Стандартная ошибка"
    unable_to_save: "Не удалось сохранить пожелание"
